### PR TITLE
[WIP] Implement creating Kubernetes masters

### PR DESCRIPTION
**Pull request by aknuds1**
Branch for implementing Kubernetes masters on DigitalOcean. Will not build at this point.

### CODE REVIEW

**Comment by aknuds1** [comment]
@alekssaul I can't build this branch due to a dependency cycle in the Terraform config apparently, would you be able to understand what's causing it?

    CLUSTER=socialfoodie PLATFORM=digitalocean make plan
    Using build directory [/Users/arve/go/src/github.com/coreos/tectonic-installer/build/socialfoodie]
    sed "s|<PATH_TO_INSTALLER>|/Users/arve/go/src/github.com/coreos/tectonic-installer/installer/bin/darwin/installer|g" terraformrc.example > .terraformrc
    cd /Users/arve/go/src/github.com/coreos/tectonic-installer/build/socialfoodie && TERRAFORM_CONFIG=/Users/arve/go/src/github.com/coreos/tectonic-installer/.terraformrc terraform get /Users/arve/go/src/github.com/coreos/tectonic-installer/platforms/digitalocean
    Get: file:///Users/arve/go/src/github.com/coreos/tectonic-installer/modules/digitalocean/etcd
    Get: file:///Users/arve/go/src/github.com/coreos/tectonic-installer/modules/digitalocean/ignition
    Get: file:///Users/arve/go/src/github.com/coreos/tectonic-installer/modules/digitalocean/master
    Get: file:///Users/arve/go/src/github.com/coreos/tectonic-installer/modules/bootkube
    Get: file:///Users/arve/go/src/github.com/coreos/tectonic-installer/modules/tectonic
    cd /Users/arve/go/src/github.com/coreos/tectonic-installer/build/socialfoodie && TERRAFORM_CONFIG=/Users/arve/go/src/github.com/coreos/tectonic-installer/.terraformrc terraform plan /Users/arve/go/src/github.com/coreos/tectonic-installer/platforms/digitalocean
    Error asking for user input: 1 error(s) occurred:

    * Cycle: module.ignition-masters.data.template_file.kubelet, module.ignition-masters.data.ignition_systemd_unit.kubelet, module.ignition-masters.data.ignition_systemd_unit.init-assets, module.ignition-masters.data.template_file.kubelet-env, module.ignition-masters.data.ignition_systemd_unit.kubelet-env, module.tectonic.var.kube_apiserver_url, module.tectonic.template_dir.tectonic, module.tectonic.output.id, module.bootkube.local_file.etcd-service, module.bootkube.local_file.etcd-operator, module.bootkube.var.oidc_issuer_url, module.bootkube.tls_cert_request.apiserver, module.bootkube.tls_locally_signed_cert.apiserver, module.bootkube.template_dir.bootkube, module.bootkube.local_file.kubeconfig, module.bootkube.output.id, data.archive_file.assets, aws_s3_bucket_object.tectonic-assets, module.ignition-masters.var.assets_s3_location, module.ignition-masters.data.template_file.init-assets, module.ignition-masters.data.ignition_file.init-assets, module.ignition-masters.data.ignition_config.main, module.ignition-masters.output.ignition, module.masters.var.user_data, module.masters.digitalocean_droplet.master_node, module.masters.digitalocean_domain.api-external, module.masters.output.api_external_fqdn, module.bootkube.var.kube_apiserver_url, module.bootkube.data.template_file.kubeconfig, module.bootkube.output.kubeconfig, aws_s3_bucket_object.kubeconfig, module.ignition-masters.var.kubeconfig_s3_location

**Comment by alekssaul** [comment]
Hi @aknuds1 ,

My recommendation would be to stay away from AWS services such as S3. We use it in AWS because it's part of the platform, however we try not to rely on AWS services on other platforms. With the exception of Openstack which is a WIP. If you look at Azure or Metal platforms, you'll see that we SCP over the contents instead of pulling them from S3. 

You may be missing a variable. Can you try to `cd /Users/arve/go/src/github.com/coreos/tectonic-installer/build/socialfoodie` , and execute `terraform plan ../../platforms/digitalocean`

**Comment by aknuds1** [comment]
@alekssaul Thanks, I guess I'll start by removing dependencies on S3.

Regarding your suggestion, executing terraform plan in that directory gives the same cycle error message. If only the message weren't so hard to understand :(

**Comment by alekssaul** [comment]
@aknuds1 : happy to help where I can. Feel free to reach out via google chat.

TF failure msges can be confusing to understand as it TF parallelize bunch of tasks.  Please let me know if you are stuck and would like me to attempt to replicate.

**Pull request merged**
